Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_1/hls4ml_prj/keras_model.h5'
OutputDir: model_1/hls4ml_prj
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: AAAFa5AC
Version: 1.0.0
